import React, { useState, useEffect } from 'react';
import { useAuth } from '../context/AuthContext';
import apiClient from '../api/client';
import { History, TrendingUp, TrendingDown, BrainCircuit } from 'lucide-react';
import { useNavigate } from 'react-router-dom';

export default function PredictionHistoryPage() {
  const { user } = useAuth();
  const navigate = useNavigate();

  const [history, setHistory] = useState([]);
  const [loading, setLoading] = useState(true);

  const fetchHistory = async () => {
    if (!user) return;
    setLoading(true);
    try {
      const res = await apiClient.get('/predict/history');
      setHistory(res.data);
    } catch (err) {
      console.error('Error fetching prediction history:', err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    if (user) {
      fetchHistory();
    } else {
      setLoading(false);
    }
  }, [user]);

  if (!user) {
    return (
      <div className="glass-card" style={{ padding: '60px', textAlign: 'center' }}>
        <History size={48} color="#8b5cf6" style={{ marginBottom: '16px' }} />
        <h2 style={{ fontSize: '20px', fontWeight: 700, color: '#ffffff' }}>User Authentication Required</h2>
        <p style={{ color: '#9ca3af', marginTop: '8px', marginBottom: '24px' }}>
          Log in to view your stored ML prediction records and track prediction accuracy error against actual market data.
        </p>
        <button className="btn-primary" onClick={() => navigate('/login')}>
          Log In / Register
        </button>
      </div>
    );
  }

  if (loading) {
    return <div style={{ padding: '40px', color: '#9ca3af' }}>Fetching Prediction History...</div>;
  }

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '24px' }}>
      {/* Header */}
      <div>
        <h1 style={{ fontSize: '24px', fontWeight: 700, color: '#f9fafb', display: 'flex', alignItems: 'center', gap: '10px' }}>
          <History size={24} color="#8b5cf6" /> User Prediction History Log
        </h1>
        <p style={{ color: '#9ca3af', fontSize: '13px', marginTop: '4px' }}>
          Persistent records of all ML predictions generated by user: {user.email}
        </p>
      </div>

      {/* History Table */}
      <div className="glass-card" style={{ padding: '20px' }}>
        <h3 style={{ fontSize: '16px', fontWeight: 600, color: '#f3f4f6', marginBottom: '16px' }}>
          Stored Prediction History ({history.length})
        </h3>

        {history.length === 0 ? (
          <div style={{ padding: '40px', textAlign: 'center', color: '#9ca3af' }}>
            No saved prediction records yet. Go to the "ML Prediction" tab to run next-day forecasts.
          </div>
        ) : (
          <div style={{ overflowX: 'auto' }}>
            <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '13px', textAlign: 'left' }}>
              <thead>
                <tr style={{ borderBottom: '1px solid #374151', color: '#9ca3af' }}>
                  <th style={{ padding: '10px' }}>ID</th>
                  <th style={{ padding: '10px' }}>Ticker</th>
                  <th style={{ padding: '10px' }}>Prediction Date</th>
                  <th style={{ padding: '10px' }}>Predicted Price</th>
                  <th style={{ padding: '10px' }}>Direction</th>
                  <th style={{ padding: '10px' }}>Model Used</th>
                  <th style={{ padding: '10px' }}>Actual Price</th>
                  <th style={{ padding: '10px' }}>Prediction Error</th>
                  <th style={{ padding: '10px' }}>Logged At</th>
                </tr>
              </thead>
              <tbody>
                {history.map((rec) => (
                  <tr key={rec.id} style={{ borderBottom: '1px solid #1f2937', color: '#e5e7eb' }}>
                    <td style={{ padding: '10px', color: '#9ca3af' }}>#{rec.id}</td>
                    <td style={{ padding: '10px', fontWeight: 700, color: '#3b82f6' }}>{rec.ticker}</td>
                    <td style={{ padding: '10px' }}>{rec.prediction_date}</td>
                    <td style={{ padding: '10px', fontWeight: 600, color: '#ffffff' }}>${rec.predicted_price.toFixed(2)}</td>
                    <td style={{ padding: '10px' }}>
                      <span className={rec.predicted_direction === 'UP' ? 'badge-up' : 'badge-down'}>
                        {rec.predicted_direction}
                      </span>
                    </td>
                    <td style={{ padding: '10px', color: '#9ca3af' }}>{rec.model_used}</td>
                    <td style={{ padding: '10px', fontWeight: 600, color: rec.actual_price ? '#10b981' : '#6b7280' }}>
                      {rec.actual_price ? `$${rec.actual_price.toFixed(2)}` : 'Pending Market Data'}
                    </td>
                    <td style={{ padding: '10px' }}>
                      {rec.prediction_error != null ? (
                        <span style={{ color: rec.prediction_error < 5.0 ? '#10b981' : '#f59e0b', fontWeight: 600 }}>
                          ${rec.prediction_error.toFixed(2)}
                        </span>
                      ) : (
                        <span style={{ color: '#6b7280' }}>-</span>
                      )}
                    </td>
                    <td style={{ padding: '10px', color: '#9ca3af' }}>
                      {new Date(rec.created_at).toLocaleString()}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </div>
  );
}
